### PR TITLE
solves #8 but you beat me with 19 minutes GG

### PR DESCRIPTION
**Pull request by D4ndellion**
I just thought I'd have some fun and make a random webpage. And you know, this happened

### CODE REVIEW

**Comment by jessferna** [comment]
Awesome. thanks, let me try that out.

**Comment by jessferna** [comment]
Thansk @dali99 it works as expected, but the pages should use Bootstrap. 

I'll update the readme.md.

p/s, I'll use your image if you're ok with that :)

**Comment by D4ndellion** [comment]
Yeah you can use my image :)

Any reason the pages should use bootstrap? Cause personally I don't like using bootstrap if I don't need too

Also I kinda cheated with my method :P
You probably shouldn't use position absolute if you want a scrollable site. Then translating with a relative position would probably be your best bet :)

**Comment by jessferna** [comment]
Ah, well.. just because I created this project to learn Bootstrap and GitHub.

Once I learn all that I will start working on a "webadmin" for a simple portfolio page or something.

**Comment by D4ndellion** [comment]
coolio

**Pull request closed without merging**
